spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spot_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-here}
    expiration: 86400000 # 24 hours in milliseconds
  cors:
    allowed-origins: 
      - http://localhost:5173 # Vite dev server
      - http://localhost:8080 # Production
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Authorization,Content-Type
    exposed-headers: Authorization

google:
  oauth2:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/google/callback}

websocket:
  endpoint: /ws
  topic-prefix: /topic
  application-prefix: /app
  allowed-origins: ${security.cors.allowed-origins}

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    edu.cit.spot: DEBUG
    org.springframework.security: INFO
