spring:
  datasource:
    url: 
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret:
            scope:
              - email
              - profile

application:
  frontend:
    url: http://localhost:5173
  security:
    jwt:
      secret: 
      expirationMs: 86400000 # 24 hours

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    filter: true
  packages-to-scan: edu.cit.spot.controller
  paths-to-match: /api/**

logging:
  level:
    org.springframework.security: INFO
    edu.cit.spot: DEBUG
